language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"

script: pytest

before_install:
  - export CFLAGS=`gdal-config --cflags`
  - export LDFLAGS=`gdal-config --libs`
  - export PROJ_LIB=/usr/share/proj

addons:
  apt:
    packages:
      - libgdal-dev
      - gdal-bin
