language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# - "nightly"

script: pytest

before_install:
  - export CPPFLAGS=`gdal-config --cflags`
  - export LDFLAGS=`gdal-config --libs`
  - export PROJ_LIB=/usr/share/proj

install:
  - pip install --use-wheel -r dev-requirements.txt
  - pip install .

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    - sourceline: 'ppa:johanvdw/gdal'
    packages:
      - libgdal-dev
      - gdal-bin
