language: python
sudo: false
cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

python:
  - "2.7"
  - "3.5"
  - "3.6"
# - "nightly"

script: pytest --cov niche_vlaanderen --cov-report term-missing

before_install:
  - export CPPFLAGS=`gdal-config --cflags`
  - export LDFLAGS=`gdal-config --libs`
  - export PROJ_LIB=/usr/share/proj

install:
  - pip install --use-wheel -r dev-requirements.txt
  - pip install coveralls
  - pip install .

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
      - gdal-bin

after_success:
  - coveralls || echo "coveralls failure"
